# This provides configuration for mkdocs documentation generation.
# For more configuration options, see https://www.mkdocs.org/user-guide/configuration/
site_name: pyOsiriX Example Project (ver 0.0.1-dev.20)
site_url:
repo_url: https://github.com/osirixgrpc/pyosirix_example_project
docs_dir: "docs"

# Copyright
copyright: Copyright &copy; Matthew D Blackledge  # Provide some copyright information if you like.
edit_uri: edit/main/docs  # If someone edits the page, where will it link to?
use_directory_urls: true
theme:
  name: material  # This theme is available through "mkdocs materials" extension.  This is a popular and powerful tool.
  locale: en  # The language of the site.
  logo: assets/logo.png  # Is there a logo?  It's not all that necessary, but here for completeness.
  highlightjs: true  # We will allow highlight.js to perform syntax coloring for us.
  favicon: assets/favicon.ico  # You can add a favicon (little logo that appears in the browser tabs - fancy!)
  hljs_languages:  # What languages will be colored?
      - python
      - console
      - toml
      - yaml
      - bash
      - shell
      - sh
  palette:
    - scheme: default  # The color scheme to use.
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
  - search
  - mkdocstrings  # This is an additional extension that creates documentation automatically from your code docstrings.
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ "." ]

# Documentation extensions.
markdown_extensions:
  - pymdownx.highlight:  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks, another useful extension.
      anchor_linenums: true  # Provide line numbers for any code snippets.
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets  # Automatically copy/paste code into your docs: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences
  - attr_list  # Attribute lists, used here for images.
  - md_in_html  # Markdown in HTML for adding markdown syntax to HTML, used here for images.
  - admonition  # For including things like tip boxes, info boxes, warnings.
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: ["."] # Where is the root of the repository?
  - pymdownx.arithmatex:
      generic: true  # Needed to include LateX in our documentation.

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js  # Also required for LateX

# Define the overall layout (tree structure) of the documentation, in the format:
#      Displayed name: docfile_page.md
# If no docfile_page is defined, this means you are defining a group of pages, tabs should be consistent.
nav:
  - Home: README.md  # Where the home page of the documentation will be stored.
  - Plugin Instructions: plugin_instructions.md
  - Project Components:
    - CI/CD with GitHub: github.md
    - Data control with DVC: dvc.md
    - Documentation with MkDocs: mkdocs.md
    - Installing pyOsiriX scripts: pyosirix.md
    - Python packaging with PIP: pip.md
    - Unit testing with PyTest: pytest.md
    - Version Control with bump2version: bumpversion.md
  - Contributing:
    - Home: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md

