# Header information
name: Bug Report
description: File a bug report
title: "Bug: "  # A placeholder for the title.
labels: ["bug"]
assignees:
  - mdblackledge  # PLEASE CHANGE! Who is automatically assigned to this bug (GH account name)

# Body information - one
body:
  # Welcome the issue reporter
  - type: markdown
    id: welcome
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  # How can we get in touch with them if needed?
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com  # The default
    validations:
      required: false

  # Ask them what happened, and how we could reproduce the bug during experimentation.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        What steps could we use to reproduce the bug?
      placeholder: |
        1. The following occurred...
        2. I expected to see...
        3. This is a copy of the error text...
        4. See attached an error file...
        5. What steps could we use to re-create the issue?
    validations:
      required: true

  # What version of the project are they using? Yse current version as placeholder.
  - type: input
    id: project-version
    attributes:
      label: Project Version
      description: What version of the project are you running?
      placeholder: "placeholder: "0.0.1-dev.27""
    validations:
      required: true

  # What version of macOS are they using?
  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      description: What version of MacOS are you running?
      placeholder: "13.0.0"
    validations:
      required: true

  # What Mac architecture are they using?
  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What Mac architecture are you using? (output of `arch` from terminal)
      options:
        - x86_64 (Intel)
        - arm64 (Apple Silicon)
      default: 0
    validations:
      required: true

  # Check they are willing to abide by our code of conduct
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
