name: Documentation
description: Improve our documentation
title: "Documentation: "
labels: ["documentation"]
assignees:
  - mdblackledge # PLEASE CHANGE! Who is automatically assigned to this bug (GH account name)
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feedback on our documentation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: project-version
    attributes:
      label: Project Version
      description: What version of the project are you running?
      placeholder: "placeholder: "0.0.1-dev.14""
    validations:
      required: true
  - type: textarea
    id: documentation-suggestion
    attributes:
      label: How could we improve our documentation?
      description: |
        Let us know in as much detail as possible which documentation needs changing and why.
      placeholder: |
        **Page link**
        Provide a link to the documentation page that needs improving.
        
        **Describe the issue with the documentation**
        A clear and concise description of what the documentation issue is.
        
        **Expected improvement**
        A clear and concise description of what you expected to find in the documentation.
        
        **Additional context**
        Add any other context about the documentation issue here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
