name: Feature Request
description: Request a new feature
title: "Feature: "
labels: ["feature_request"]
assignees:
  - mdblackledge # PLEASE CHANGE! Who is automatically assigned to this bug (GH account name)
body:
  - type: markdown
    attributes:
      value: |
        Thanks for offering suggestions for new features!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: project-version
    attributes:
      label: Project Version
      description: What version of the project are you running?
      placeholder: "placeholder: "0.0.1-dev1""
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see?
      description: |
        Let us know in as much detail as possible what it is you need and why. 
        If helpful, please do attach some screenshots or figure that might help explain this a little better.
      placeholder: |
        **Short description of the new functionality**
        What would you like the new functionality to achieve?
        
        **Why would this improve the functionality of this project?**
        Why does this matter to you?
        
        **Have you been using any work-around so far?**
        Please let us know how much of an issue this has been for you.
        
        **How urgent is the new functionality to you?**
        Does the project fail to meet your needs without?
        
        **Would you be willing to help develop/test the new functionality?**
        Please contact us if so.

        **Additional context**
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
