name: MkDocs Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build MkDocs Site
        run: mkdocs build
    
      - name: Deploy docs to GitHub Pages
        run: mkdocs gh-deploy --force