name: Run unit tests  # The name of the action (as displayed on GitHub)

# When do you want the action to occur? Aat present this will only run when pushing to main branch.
on:
  push:
    branches:
      - main
      - dev

# Tell GH the jobs you want to perform.
# Side note: Some of these keywords cannot be changed (jobs, runs-on, steps), but some are flexible (e.g. run-tests).
jobs:
  run-tests:  # We can call this anything we like that makes sense.
    runs-on: macos-latest  # We will run on this on macOS as that is the final destination.

    # Define each step for the "run-tests" job.
    steps:
      # Checkout the latest code
      - name: Checkout
        uses: actions/checkout@v4  # This s a pre-built "action" that someone else has kindly made. It is used frequently!

      # Install python on the shiny new macOS server.
      - name: Set up Python
        uses: actions/setup-python@v5  # Another pre-built action.
        with:
          python-version: 3

      # Build gRPC libraries
      - name: Build gRPC Files Workflow
        uses: ./.github/workflows/build_grpc_files.yaml  # Calls the reusable workflow

      # Install all our dependencies.
      - name: Install dependencies
        run: |  # Using a "|" symbol allows you to use a multiline command.
          python3 -m pip install -r requirements.txt
          python3 -m pip install setuptools pytest

      # Run the tests, just as you would run it from Terminal.
      - name: Unit tests
        run: python -m pytest tests